/********************************************************************************
** Form generated from reading UI file 'LayersOptionDialog.ui'
**
** Created by: Qt User Interface Compiler version 5.8.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_LAYERSOPTIONDIALOG_H
#define UI_LAYERSOPTIONDIALOG_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_LayersOptionDialog
{
public:
    QPushButton *pushButtonCancel;
    QGroupBox *groupBox;
    QLabel *label;
    QLineEdit *lineEditCurveMinAngle;
    QLineEdit *lineEditCurveNumIterations;
    QLabel *label_5;
    QLineEdit *lineEditCurveMaxRadius;
    QLineEdit *lineEditCurveMinRadius;
    QLineEdit *lineEditCurveMaxErrorRatioToRadius;
    QLabel *label_2;
    QLabel *label_6;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *label_7;
    QLineEdit *lineEditCurveMinPoints;
    QLineEdit *lineEditCurveClusterEpsilon;
    QLabel *label_14;
    QGroupBox *groupBox_2;
    QLineEdit *lineEditLineMinLength;
    QLineEdit *lineEditLineClusterEpsilon;
    QLineEdit *lineEditLineMinPoints;
    QLineEdit *lineEditLineMaxError;
    QLineEdit *lineEditLineNumIterations;
    QLabel *label_8;
    QLabel *label_9;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLineEdit *lineEditLineAngleThreshold;
    QLabel *label_13;
    QLabel *label_15;
    QLabel *label_19;
    QLineEdit *lineEditRAMaxError;
    QLineEdit *lineEditRAClusterEpsilon;
    QCheckBox *checkBoxUseRA;
    QCheckBox *checkBoxRAOptimization;
    QLabel *label_20;
    QPushButton *pushButtonOK;
    QGroupBox *groupBox_4;
    QLabel *label_21;
    QLabel *label_22;
    QLineEdit *lineEditInput;
    QLineEdit *lineEditOutput;
    QPushButton *pushButtonInput;
    QPushButton *pushButtonOutput;
    QGroupBox *groupBox_3;
    QLabel *label_16;
    QLineEdit *lineEditContourMaxError;
    QLineEdit *lineEditContourAngleThreshold;
    QLabel *label_17;
    QLabel *label_18;
    QGroupBox *groupBox_5;
    QLabel *label_31;
    QLabel *label_27;
    QLineEdit *lineEditParallelThreshold;
    QCheckBox *checkBoxSymmetryLine;
    QLabel *label_25;
    QCheckBox *checkBoxRA;
    QLabel *label_26;
    QLabel *label_24;
    QLabel *label_23;
    QLabel *label_32;
    QLineEdit *lineEditSymmetryWeight;
    QLineEdit *lineEditIOUThreshold;
    QLabel *label_28;
    QLabel *label_29;
    QLabel *label_30;
    QCheckBox *checkBoxAccuracy;
    QLineEdit *lineEditAccuracyWeight;
    QLineEdit *lineEditRaWeight;
    QLineEdit *lineEditRAthreshold;
    QLineEdit *lineEditParallelWeight;
    QCheckBox *checkBoxParallel;
    QGroupBox *groupBox_6;
    QLabel *label_33;
    QLabel *label_34;
    QLineEdit *lineEditSegDisThreshold;
    QLabel *label_35;
    QLineEdit *lineEditSegAngleThreshold;
    QCheckBox *checkBoxPointSnap;
    QLabel *label_36;
    QLineEdit *lineEditPointDisThreshold;
    QCheckBox *checkBoxSegSnap;
    QLabel *label_37;
    QLineEdit *lineEditPointWeight;
    QLabel *label_38;
    QLineEdit *lineEditSegWeight;
    QGroupBox *groupBox_7;
    QLabel *label_39;
    QLineEdit *lineEditIntraWeight;
    QLineEdit *lineEditInterWeight;
    QLabel *label_40;
    QCheckBox *checkBoxUseIntra;
    QCheckBox *checkBoxUseInter;

    void setupUi(QDialog *LayersOptionDialog)
    {
        if (LayersOptionDialog->objectName().isEmpty())
            LayersOptionDialog->setObjectName(QStringLiteral("LayersOptionDialog"));
        LayersOptionDialog->resize(639, 777);
        pushButtonCancel = new QPushButton(LayersOptionDialog);
        pushButtonCancel->setObjectName(QStringLiteral("pushButtonCancel"));
        pushButtonCancel->setGeometry(QRect(497, 737, 91, 31));
        groupBox = new QGroupBox(LayersOptionDialog);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 66, 281, 241));
        label = new QLabel(groupBox);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(10, 40, 81, 16));
        lineEditCurveMinAngle = new QLineEdit(groupBox);
        lineEditCurveMinAngle->setObjectName(QStringLiteral("lineEditCurveMinAngle"));
        lineEditCurveMinAngle->setGeometry(QRect(140, 100, 101, 20));
        lineEditCurveNumIterations = new QLineEdit(groupBox);
        lineEditCurveNumIterations->setObjectName(QStringLiteral("lineEditCurveNumIterations"));
        lineEditCurveNumIterations->setGeometry(QRect(140, 20, 101, 20));
        label_5 = new QLabel(groupBox);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(10, 120, 131, 16));
        lineEditCurveMaxRadius = new QLineEdit(groupBox);
        lineEditCurveMaxRadius->setObjectName(QStringLiteral("lineEditCurveMaxRadius"));
        lineEditCurveMaxRadius->setGeometry(QRect(140, 140, 101, 20));
        lineEditCurveMinRadius = new QLineEdit(groupBox);
        lineEditCurveMinRadius->setObjectName(QStringLiteral("lineEditCurveMinRadius"));
        lineEditCurveMinRadius->setGeometry(QRect(140, 120, 101, 20));
        lineEditCurveMaxErrorRatioToRadius = new QLineEdit(groupBox);
        lineEditCurveMaxErrorRatioToRadius->setObjectName(QStringLiteral("lineEditCurveMaxErrorRatioToRadius"));
        lineEditCurveMaxErrorRatioToRadius->setGeometry(QRect(140, 60, 101, 20));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 60, 131, 16));
        label_6 = new QLabel(groupBox);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(10, 140, 131, 16));
        label_3 = new QLabel(groupBox);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(10, 80, 131, 16));
        label_4 = new QLabel(groupBox);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(10, 100, 131, 16));
        label_7 = new QLabel(groupBox);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(10, 20, 81, 16));
        lineEditCurveMinPoints = new QLineEdit(groupBox);
        lineEditCurveMinPoints->setObjectName(QStringLiteral("lineEditCurveMinPoints"));
        lineEditCurveMinPoints->setGeometry(QRect(140, 40, 101, 20));
        lineEditCurveClusterEpsilon = new QLineEdit(groupBox);
        lineEditCurveClusterEpsilon->setObjectName(QStringLiteral("lineEditCurveClusterEpsilon"));
        lineEditCurveClusterEpsilon->setGeometry(QRect(140, 80, 101, 20));
        label_14 = new QLabel(groupBox);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(250, 100, 31, 16));
        groupBox_2 = new QGroupBox(LayersOptionDialog);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(340, 66, 281, 241));
        lineEditLineMinLength = new QLineEdit(groupBox_2);
        lineEditLineMinLength->setObjectName(QStringLiteral("lineEditLineMinLength"));
        lineEditLineMinLength->setGeometry(QRect(140, 100, 101, 20));
        lineEditLineClusterEpsilon = new QLineEdit(groupBox_2);
        lineEditLineClusterEpsilon->setObjectName(QStringLiteral("lineEditLineClusterEpsilon"));
        lineEditLineClusterEpsilon->setGeometry(QRect(140, 80, 101, 20));
        lineEditLineMinPoints = new QLineEdit(groupBox_2);
        lineEditLineMinPoints->setObjectName(QStringLiteral("lineEditLineMinPoints"));
        lineEditLineMinPoints->setGeometry(QRect(140, 40, 101, 20));
        lineEditLineMaxError = new QLineEdit(groupBox_2);
        lineEditLineMaxError->setObjectName(QStringLiteral("lineEditLineMaxError"));
        lineEditLineMaxError->setGeometry(QRect(140, 60, 101, 20));
        lineEditLineNumIterations = new QLineEdit(groupBox_2);
        lineEditLineNumIterations->setObjectName(QStringLiteral("lineEditLineNumIterations"));
        lineEditLineNumIterations->setGeometry(QRect(140, 20, 101, 20));
        label_8 = new QLabel(groupBox_2);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(10, 80, 131, 16));
        label_9 = new QLabel(groupBox_2);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(10, 20, 81, 16));
        label_10 = new QLabel(groupBox_2);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(10, 40, 81, 16));
        label_11 = new QLabel(groupBox_2);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(10, 100, 131, 16));
        label_12 = new QLabel(groupBox_2);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(10, 60, 131, 16));
        lineEditLineAngleThreshold = new QLineEdit(groupBox_2);
        lineEditLineAngleThreshold->setObjectName(QStringLiteral("lineEditLineAngleThreshold"));
        lineEditLineAngleThreshold->setGeometry(QRect(140, 120, 101, 20));
        label_13 = new QLabel(groupBox_2);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(10, 120, 131, 16));
        label_15 = new QLabel(groupBox_2);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(250, 120, 31, 16));
        label_19 = new QLabel(groupBox_2);
        label_19->setObjectName(QStringLiteral("label_19"));
        label_19->setGeometry(QRect(10, 170, 131, 16));
        lineEditRAMaxError = new QLineEdit(groupBox_2);
        lineEditRAMaxError->setObjectName(QStringLiteral("lineEditRAMaxError"));
        lineEditRAMaxError->setGeometry(QRect(140, 170, 101, 20));
        lineEditRAClusterEpsilon = new QLineEdit(groupBox_2);
        lineEditRAClusterEpsilon->setObjectName(QStringLiteral("lineEditRAClusterEpsilon"));
        lineEditRAClusterEpsilon->setGeometry(QRect(140, 190, 101, 20));
        checkBoxUseRA = new QCheckBox(groupBox_2);
        checkBoxUseRA->setObjectName(QStringLiteral("checkBoxUseRA"));
        checkBoxUseRA->setGeometry(QRect(10, 150, 141, 17));
        checkBoxRAOptimization = new QCheckBox(groupBox_2);
        checkBoxRAOptimization->setObjectName(QStringLiteral("checkBoxRAOptimization"));
        checkBoxRAOptimization->setGeometry(QRect(10, 210, 101, 17));
        label_20 = new QLabel(groupBox_2);
        label_20->setObjectName(QStringLiteral("label_20"));
        label_20->setGeometry(QRect(10, 190, 131, 16));
        pushButtonOK = new QPushButton(LayersOptionDialog);
        pushButtonOK->setObjectName(QStringLiteral("pushButtonOK"));
        pushButtonOK->setGeometry(QRect(367, 737, 91, 31));
        groupBox_4 = new QGroupBox(LayersOptionDialog);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(11, 5, 611, 51));
        label_21 = new QLabel(groupBox_4);
        label_21->setObjectName(QStringLiteral("label_21"));
        label_21->setGeometry(QRect(10, 20, 47, 13));
        label_22 = new QLabel(groupBox_4);
        label_22->setObjectName(QStringLiteral("label_22"));
        label_22->setGeometry(QRect(340, 20, 47, 13));
        lineEditInput = new QLineEdit(groupBox_4);
        lineEditInput->setObjectName(QStringLiteral("lineEditInput"));
        lineEditInput->setGeometry(QRect(50, 20, 161, 20));
        lineEditOutput = new QLineEdit(groupBox_4);
        lineEditOutput->setObjectName(QStringLiteral("lineEditOutput"));
        lineEditOutput->setGeometry(QRect(380, 20, 161, 20));
        pushButtonInput = new QPushButton(groupBox_4);
        pushButtonInput->setObjectName(QStringLiteral("pushButtonInput"));
        pushButtonInput->setGeometry(QRect(220, 20, 51, 23));
        pushButtonOutput = new QPushButton(groupBox_4);
        pushButtonOutput->setObjectName(QStringLiteral("pushButtonOutput"));
        pushButtonOutput->setGeometry(QRect(550, 20, 51, 23));
        groupBox_3 = new QGroupBox(LayersOptionDialog);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 316, 611, 51));
        label_16 = new QLabel(groupBox_3);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 20, 91, 16));
        lineEditContourMaxError = new QLineEdit(groupBox_3);
        lineEditContourMaxError->setObjectName(QStringLiteral("lineEditContourMaxError"));
        lineEditContourMaxError->setGeometry(QRect(140, 20, 101, 20));
        lineEditContourAngleThreshold = new QLineEdit(groupBox_3);
        lineEditContourAngleThreshold->setObjectName(QStringLiteral("lineEditContourAngleThreshold"));
        lineEditContourAngleThreshold->setGeometry(QRect(470, 20, 101, 20));
        label_17 = new QLabel(groupBox_3);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(340, 20, 91, 16));
        label_18 = new QLabel(groupBox_3);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(580, 19, 31, 16));
        groupBox_5 = new QGroupBox(LayersOptionDialog);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(10, 458, 611, 151));
        label_31 = new QLabel(groupBox_5);
        label_31->setObjectName(QStringLiteral("label_31"));
        label_31->setGeometry(QRect(10, 119, 47, 13));
        label_27 = new QLabel(groupBox_5);
        label_27->setObjectName(QStringLiteral("label_27"));
        label_27->setGeometry(QRect(580, 39, 31, 16));
        lineEditParallelThreshold = new QLineEdit(groupBox_5);
        lineEditParallelThreshold->setObjectName(QStringLiteral("lineEditParallelThreshold"));
        lineEditParallelThreshold->setGeometry(QRect(140, 99, 101, 22));
        checkBoxSymmetryLine = new QCheckBox(groupBox_5);
        checkBoxSymmetryLine->setObjectName(QStringLiteral("checkBoxSymmetryLine"));
        checkBoxSymmetryLine->setGeometry(QRect(10, 19, 131, 17));
        label_25 = new QLabel(groupBox_5);
        label_25->setObjectName(QStringLiteral("label_25"));
        label_25->setGeometry(QRect(340, 39, 121, 16));
        checkBoxRA = new QCheckBox(groupBox_5);
        checkBoxRA->setObjectName(QStringLiteral("checkBoxRA"));
        checkBoxRA->setGeometry(QRect(340, 19, 81, 20));
        label_26 = new QLabel(groupBox_5);
        label_26->setObjectName(QStringLiteral("label_26"));
        label_26->setGeometry(QRect(250, 99, 31, 21));
        label_24 = new QLabel(groupBox_5);
        label_24->setObjectName(QStringLiteral("label_24"));
        label_24->setGeometry(QRect(250, 39, 47, 13));
        label_23 = new QLabel(groupBox_5);
        label_23->setObjectName(QStringLiteral("label_23"));
        label_23->setGeometry(QRect(10, 39, 131, 16));
        label_32 = new QLabel(groupBox_5);
        label_32->setObjectName(QStringLiteral("label_32"));
        label_32->setGeometry(QRect(340, 99, 47, 13));
        lineEditSymmetryWeight = new QLineEdit(groupBox_5);
        lineEditSymmetryWeight->setObjectName(QStringLiteral("lineEditSymmetryWeight"));
        lineEditSymmetryWeight->setGeometry(QRect(140, 59, 101, 20));
        lineEditIOUThreshold = new QLineEdit(groupBox_5);
        lineEditIOUThreshold->setObjectName(QStringLiteral("lineEditIOUThreshold"));
        lineEditIOUThreshold->setGeometry(QRect(140, 39, 101, 20));
        label_28 = new QLabel(groupBox_5);
        label_28->setObjectName(QStringLiteral("label_28"));
        label_28->setGeometry(QRect(10, 99, 94, 16));
        label_29 = new QLabel(groupBox_5);
        label_29->setObjectName(QStringLiteral("label_29"));
        label_29->setGeometry(QRect(10, 59, 47, 13));
        label_30 = new QLabel(groupBox_5);
        label_30->setObjectName(QStringLiteral("label_30"));
        label_30->setGeometry(QRect(340, 59, 47, 13));
        checkBoxAccuracy = new QCheckBox(groupBox_5);
        checkBoxAccuracy->setObjectName(QStringLiteral("checkBoxAccuracy"));
        checkBoxAccuracy->setGeometry(QRect(340, 79, 131, 17));
        lineEditAccuracyWeight = new QLineEdit(groupBox_5);
        lineEditAccuracyWeight->setObjectName(QStringLiteral("lineEditAccuracyWeight"));
        lineEditAccuracyWeight->setGeometry(QRect(470, 99, 101, 20));
        lineEditRaWeight = new QLineEdit(groupBox_5);
        lineEditRaWeight->setObjectName(QStringLiteral("lineEditRaWeight"));
        lineEditRaWeight->setGeometry(QRect(470, 59, 101, 20));
        lineEditRAthreshold = new QLineEdit(groupBox_5);
        lineEditRAthreshold->setObjectName(QStringLiteral("lineEditRAthreshold"));
        lineEditRAthreshold->setGeometry(QRect(470, 39, 101, 22));
        lineEditParallelWeight = new QLineEdit(groupBox_5);
        lineEditParallelWeight->setObjectName(QStringLiteral("lineEditParallelWeight"));
        lineEditParallelWeight->setGeometry(QRect(140, 119, 101, 20));
        checkBoxParallel = new QCheckBox(groupBox_5);
        checkBoxParallel->setObjectName(QStringLiteral("checkBoxParallel"));
        checkBoxParallel->setGeometry(QRect(10, 79, 121, 20));
        groupBox_6 = new QGroupBox(LayersOptionDialog);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(10, 618, 611, 111));
        label_33 = new QLabel(groupBox_6);
        label_33->setObjectName(QStringLiteral("label_33"));
        label_33->setGeometry(QRect(580, 61, 31, 16));
        label_34 = new QLabel(groupBox_6);
        label_34->setObjectName(QStringLiteral("label_34"));
        label_34->setGeometry(QRect(340, 39, 91, 16));
        lineEditSegDisThreshold = new QLineEdit(groupBox_6);
        lineEditSegDisThreshold->setObjectName(QStringLiteral("lineEditSegDisThreshold"));
        lineEditSegDisThreshold->setGeometry(QRect(470, 39, 101, 20));
        label_35 = new QLabel(groupBox_6);
        label_35->setObjectName(QStringLiteral("label_35"));
        label_35->setGeometry(QRect(340, 59, 91, 16));
        lineEditSegAngleThreshold = new QLineEdit(groupBox_6);
        lineEditSegAngleThreshold->setObjectName(QStringLiteral("lineEditSegAngleThreshold"));
        lineEditSegAngleThreshold->setGeometry(QRect(470, 59, 101, 20));
        checkBoxPointSnap = new QCheckBox(groupBox_6);
        checkBoxPointSnap->setObjectName(QStringLiteral("checkBoxPointSnap"));
        checkBoxPointSnap->setGeometry(QRect(10, 20, 121, 17));
        label_36 = new QLabel(groupBox_6);
        label_36->setObjectName(QStringLiteral("label_36"));
        label_36->setGeometry(QRect(10, 39, 91, 16));
        lineEditPointDisThreshold = new QLineEdit(groupBox_6);
        lineEditPointDisThreshold->setObjectName(QStringLiteral("lineEditPointDisThreshold"));
        lineEditPointDisThreshold->setGeometry(QRect(140, 39, 101, 20));
        checkBoxSegSnap = new QCheckBox(groupBox_6);
        checkBoxSegSnap->setObjectName(QStringLiteral("checkBoxSegSnap"));
        checkBoxSegSnap->setGeometry(QRect(340, 20, 141, 17));
        label_37 = new QLabel(groupBox_6);
        label_37->setObjectName(QStringLiteral("label_37"));
        label_37->setGeometry(QRect(10, 59, 47, 13));
        lineEditPointWeight = new QLineEdit(groupBox_6);
        lineEditPointWeight->setObjectName(QStringLiteral("lineEditPointWeight"));
        lineEditPointWeight->setGeometry(QRect(140, 59, 101, 20));
        label_38 = new QLabel(groupBox_6);
        label_38->setObjectName(QStringLiteral("label_38"));
        label_38->setGeometry(QRect(340, 79, 47, 13));
        lineEditSegWeight = new QLineEdit(groupBox_6);
        lineEditSegWeight->setObjectName(QStringLiteral("lineEditSegWeight"));
        lineEditSegWeight->setGeometry(QRect(470, 79, 101, 20));
        groupBox_7 = new QGroupBox(LayersOptionDialog);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(10, 380, 611, 71));
        label_39 = new QLabel(groupBox_7);
        label_39->setObjectName(QStringLiteral("label_39"));
        label_39->setGeometry(QRect(10, 39, 111, 16));
        lineEditIntraWeight = new QLineEdit(groupBox_7);
        lineEditIntraWeight->setObjectName(QStringLiteral("lineEditIntraWeight"));
        lineEditIntraWeight->setGeometry(QRect(140, 39, 101, 20));
        lineEditInterWeight = new QLineEdit(groupBox_7);
        lineEditInterWeight->setObjectName(QStringLiteral("lineEditInterWeight"));
        lineEditInterWeight->setGeometry(QRect(470, 39, 101, 20));
        label_40 = new QLabel(groupBox_7);
        label_40->setObjectName(QStringLiteral("label_40"));
        label_40->setGeometry(QRect(340, 39, 111, 16));
        checkBoxUseIntra = new QCheckBox(groupBox_7);
        checkBoxUseIntra->setObjectName(QStringLiteral("checkBoxUseIntra"));
        checkBoxUseIntra->setGeometry(QRect(10, 20, 101, 17));
        checkBoxUseInter = new QCheckBox(groupBox_7);
        checkBoxUseInter->setObjectName(QStringLiteral("checkBoxUseInter"));
        checkBoxUseInter->setGeometry(QRect(340, 20, 101, 17));

        retranslateUi(LayersOptionDialog);

        QMetaObject::connectSlotsByName(LayersOptionDialog);
    } // setupUi

    void retranslateUi(QDialog *LayersOptionDialog)
    {
        LayersOptionDialog->setWindowTitle(QApplication::translate("LayersOptionDialog", "LayersOptionDialog", Q_NULLPTR));
        pushButtonCancel->setText(QApplication::translate("LayersOptionDialog", "Cancel", Q_NULLPTR));
        groupBox->setTitle(QApplication::translate("LayersOptionDialog", "Curve", Q_NULLPTR));
        label->setText(QApplication::translate("LayersOptionDialog", "Min points:", Q_NULLPTR));
        label_5->setText(QApplication::translate("LayersOptionDialog", "Min radius:", Q_NULLPTR));
        label_2->setText(QApplication::translate("LayersOptionDialog", "Max error ratio to radius:", Q_NULLPTR));
        label_6->setText(QApplication::translate("LayersOptionDialog", "Max radius:", Q_NULLPTR));
        label_3->setText(QApplication::translate("LayersOptionDialog", "Cluster epsilon:", Q_NULLPTR));
        label_4->setText(QApplication::translate("LayersOptionDialog", "Min angle:", Q_NULLPTR));
        label_7->setText(QApplication::translate("LayersOptionDialog", "# iterations:", Q_NULLPTR));
        label_14->setText(QApplication::translate("LayersOptionDialog", "[deg]", Q_NULLPTR));
        groupBox_2->setTitle(QApplication::translate("LayersOptionDialog", "Line", Q_NULLPTR));
        label_8->setText(QApplication::translate("LayersOptionDialog", "Cluster epsilon:", Q_NULLPTR));
        label_9->setText(QApplication::translate("LayersOptionDialog", "# iterations:", Q_NULLPTR));
        label_10->setText(QApplication::translate("LayersOptionDialog", "Min points:", Q_NULLPTR));
        label_11->setText(QApplication::translate("LayersOptionDialog", "Min length:", Q_NULLPTR));
        label_12->setText(QApplication::translate("LayersOptionDialog", "Max error:", Q_NULLPTR));
        label_13->setText(QApplication::translate("LayersOptionDialog", "Angle threshold:", Q_NULLPTR));
        label_15->setText(QApplication::translate("LayersOptionDialog", "[deg]", Q_NULLPTR));
        label_19->setText(QApplication::translate("LayersOptionDialog", "Max error:", Q_NULLPTR));
        checkBoxUseRA->setText(QApplication::translate("LayersOptionDialog", "Use right angle method", Q_NULLPTR));
        checkBoxRAOptimization->setText(QApplication::translate("LayersOptionDialog", "Optimization", Q_NULLPTR));
        label_20->setText(QApplication::translate("LayersOptionDialog", "Cluster epsilon:", Q_NULLPTR));
        pushButtonOK->setText(QApplication::translate("LayersOptionDialog", "OK", Q_NULLPTR));
        groupBox_4->setTitle(QApplication::translate("LayersOptionDialog", "Data", Q_NULLPTR));
        label_21->setText(QApplication::translate("LayersOptionDialog", "Input", Q_NULLPTR));
        label_22->setText(QApplication::translate("LayersOptionDialog", "Output", Q_NULLPTR));
        pushButtonInput->setText(QApplication::translate("LayersOptionDialog", "...", Q_NULLPTR));
        pushButtonOutput->setText(QApplication::translate("LayersOptionDialog", "...", Q_NULLPTR));
        groupBox_3->setTitle(QApplication::translate("LayersOptionDialog", "Contour", Q_NULLPTR));
        label_16->setText(QApplication::translate("LayersOptionDialog", "Max error:", Q_NULLPTR));
        label_17->setText(QApplication::translate("LayersOptionDialog", "Angle threshold:", Q_NULLPTR));
        label_18->setText(QApplication::translate("LayersOptionDialog", "[deg]", Q_NULLPTR));
        groupBox_5->setTitle(QApplication::translate("LayersOptionDialog", "Intra- layer Optimization", Q_NULLPTR));
        label_31->setText(QApplication::translate("LayersOptionDialog", "Weight:", Q_NULLPTR));
        label_27->setText(QApplication::translate("LayersOptionDialog", "[deg]", Q_NULLPTR));
        checkBoxSymmetryLine->setText(QApplication::translate("LayersOptionDialog", "Use symmetry line", Q_NULLPTR));
        label_25->setText(QApplication::translate("LayersOptionDialog", "RA angle threshold:", Q_NULLPTR));
        checkBoxRA->setText(QApplication::translate("LayersOptionDialog", "Use RA", Q_NULLPTR));
        label_26->setText(QApplication::translate("LayersOptionDialog", "[deg]", Q_NULLPTR));
        label_24->setText(QApplication::translate("LayersOptionDialog", "[%]", Q_NULLPTR));
        label_23->setText(QApplication::translate("LayersOptionDialog", "IOU threshold:", Q_NULLPTR));
        label_32->setText(QApplication::translate("LayersOptionDialog", "Weight:", Q_NULLPTR));
        label_28->setText(QApplication::translate("LayersOptionDialog", "Angle threshold:", Q_NULLPTR));
        label_29->setText(QApplication::translate("LayersOptionDialog", "Weight:", Q_NULLPTR));
        label_30->setText(QApplication::translate("LayersOptionDialog", "Weight:", Q_NULLPTR));
        checkBoxAccuracy->setText(QApplication::translate("LayersOptionDialog", "Use accuracy", Q_NULLPTR));
        checkBoxParallel->setText(QApplication::translate("LayersOptionDialog", "Use parallelism:", Q_NULLPTR));
        groupBox_6->setTitle(QApplication::translate("LayersOptionDialog", "Inter-layer Optimization", Q_NULLPTR));
        label_33->setText(QApplication::translate("LayersOptionDialog", "[deg]", Q_NULLPTR));
        label_34->setText(QApplication::translate("LayersOptionDialog", "Max error:", Q_NULLPTR));
        label_35->setText(QApplication::translate("LayersOptionDialog", "Angle threshold:", Q_NULLPTR));
        checkBoxPointSnap->setText(QApplication::translate("LayersOptionDialog", "Use Point Snapping", Q_NULLPTR));
        label_36->setText(QApplication::translate("LayersOptionDialog", "Dis threshold:", Q_NULLPTR));
        checkBoxSegSnap->setText(QApplication::translate("LayersOptionDialog", "Use Segments Snapping", Q_NULLPTR));
        label_37->setText(QApplication::translate("LayersOptionDialog", "Weight:", Q_NULLPTR));
        label_38->setText(QApplication::translate("LayersOptionDialog", "Weight:", Q_NULLPTR));
        groupBox_7->setTitle(QApplication::translate("LayersOptionDialog", "Optimization Weights", Q_NULLPTR));
        label_39->setText(QApplication::translate("LayersOptionDialog", "Intra-layer Weight:", Q_NULLPTR));
        label_40->setText(QApplication::translate("LayersOptionDialog", "Inter-layer Weight:", Q_NULLPTR));
        checkBoxUseIntra->setText(QApplication::translate("LayersOptionDialog", "Use Intra-layer", Q_NULLPTR));
        checkBoxUseInter->setText(QApplication::translate("LayersOptionDialog", "Use Inter-layer", Q_NULLPTR));
    } // retranslateUi

};

namespace Ui {
    class LayersOptionDialog: public Ui_LayersOptionDialog {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_LAYERSOPTIONDIALOG_H
